FROM openjdk:8u151-jdk-alpine3.7
MAINTAINER Conecta <oss@conecta.im>
RUN apk --update add bash openssl apr libuuid
ADD target/docker/stage/var /var
ADD templates /var/lib/actor/templates
ENTRYPOINT bin/conecta-server
WORKDIR /var/lib/actor
EXPOSE 9070 9080 9090